name: diesel_powered
description: Diesel Powered App.

publish_to: "none"

version: 1.0.0+14

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.19.0

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.7.0

  #Riverpod
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.3.4

  #DI
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_svg: ^2.0.4

  #DB
  hive_flutter: ^1.1.0

  #Network
  http: ^1.2.1

  #Information
  logger: ^1.3.0

  #toast
  fluttertoast: ^8.2.1

  #google_maps
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.8

  #image
  cached_network_image: ^3.2.3
  firebase_core: ^2.27.2
  flutter_keyboard_visibility: ^6.0.0
  easy_date_timeline: ^1.0.3
  permission_handler: ^11.3.1
  image_picker: ^1.0.8
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  share_plus: ^7.2.0
  calendar_date_picker2: ^1.0.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  riverpod_generator: ^2.3.11

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/pngs/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/font/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/font/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/font/SF-Pro-Display-SemiBold.ttf
          weight: 600
        - asset: assets/font/SF-Pro-Display-Bold.ttf
          weight: 700
